// This script is automatically generated by AssetManager.cs
public struct Prefab {
	public enum Debugger {
		Sphere_1,
	}
	public enum General {
		Cube_1,
		GolfBall,
		ZombieCharacter_1,
	}
	public enum UI {
		SpawnButton_1,
	}
}