// This script's automatically generated by AssetManager.cs
public struct Prefab {
	public enum Debugger {
		Box_1,
		Sphere_1,
		System_LevelEditorManager,
	}
	public enum PO {
		PC_PlayerSpawnPoint,
		PC_ZombieCharacter_1,
		PE_Tree_1,
		PE_Tree_2,
		PE_Tree_3,
		PE_Tree_4,
		PG_Dirt,
		PG_DirtAndGrass,
		PG_Grass,
		PG_Green,
		PG_Invisible,
		PG_Sand,
		PG_Sand_Edge,
		PG_Uphill_1,
		PG_Uphill_2,
		PG_Uphill_3,
		PG_Uphill_4,
		PG_Uphill_5,
		PG_Water,
		PG_WaterEdge,
		PP_GolfBag,
		PP_GolfBall,
		PP_GolfCart,
		PP_Placard,
	}
	public enum Prob {
		Camera_GolfBall,
		Camera_Green,
	}
	public enum UI {
		CanvasGroup_BlackScreen,
		DamageText,
		SpawnButton_1,
	}
	public enum VFX {
		Aura,
		Dirt,
	}
}

