// This script's automatically generated by AssetManager.cs
public struct Prefab {
	public enum Debugger {
		Box_1,
		Sphere_1,
		System_LevelEditorManager,
	}
	public enum General {
		PE_Grass_1,
		PE_Grass_2,
		PE_Tree_1,
		PE_Tree_2,
		PO_GolfBag,
		PO_GolfBall,
		PO_GolfCart,
		PO_GreenWithHole,
		PO_Ground_1,
		PO_Ground_2,
		PO_Ground_3,
		PO_PlayerSpawnPoint,
		PO_Sand,
		PO_Sand_Edge,
		PO_Uphill_1,
		PO_Uphill_2,
		PO_Uphill_3,
		PO_Uphill_4,
		PO_Uphill_5,
		PO_ZombieCharacter_1,
	}
	public enum UI {
		DamageText,
		SpawnButton_1,
	}
	public enum VFX {
		Aura,
	}
}

